---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"
  
  tasks:
    #  Delete an Address Block in a given IP space
    - name: Delete ipv4 reservation address.
      b1_ipam_ipv4_reservation:
        address: "40.0.0.1"
        space: "qa-space-1"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: absent