---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"
  
  tasks:
    #  Update the ipv4 reserved address in a given IP space
    - name: Update ipv4 reserved address in a given IP Space
      b1_ipam_ipv4_reservation:
        space: "qa-space-1"
        address: '{"new_address": "40.0.0.101", "old_address": "40.0.0.100"}'
        name: "qa-reservation-updated"
        comment: "This is the test address-mod"
        tags:
          - "Org": "Infoblox"
          - "Dept": "Engineering"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present