---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: GET all DNS View
      b1_dns_view:
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: get