---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Gather all AddressBlock
    - name: Gather Address block
      b1_ipam_address_block_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: address_block
    - debug: msg="{{ address_block }}"