---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Create a Address Block in a given IP space
    - name: Create Address Block in a given IP Space
      b1_ipam_address_block:
        space: "qa-apace-1"
        address: "40.0.0.0/16"
        name: "qa-block-updated"
        comment: "This is created by QA"
        tags:
          - "Org": "Infoblox"
          - "Dept": "Engineering"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present
