---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: Create Address Block using next-available subnet
      b1_ipam_subnet:
        space: "qa-space-1"
        address: '{"next_available_subnet": {"cidr": "28", "count": "2", "parent_block": "40.0.0.0/24"}}'
        name: "qa-test-nextAvailable"
        comment: "This is the test subnet creation using nextavailable"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present