---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Create a Subnet in a given IP space
    - name: Create Subnet in a given IP Space
      b1_ipam_subnet:
        space: "qa-space-1"
        address: "40.0.0.0/25"
        name: "qa-test-Subnet1"
        comment: "This is the subnet created by QA"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present