---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
  #  Gather Subnet with multiple filters.
    - name: Gather Subnet with a given tag
      b1_ipam_subnet_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['id', 'dhcp_options', 'tags' ]
        filters: {'name': 'qa-test-Subnet1', 'address':'40.0.0.0'}
      register: subnet
    - debug: msg="{{ subnet }}"