---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Gather Subnet with filters and fields.
    - name: Gather the Subnet detail
      b1_ipam_subnet_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
        fields: ['id', 'name', 'dhcp_options', 'tags' ]
        filters: {'address': '40.0.0.0/25'}
      register: subnet
    - debug: msg="{{ subnet }}"