---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"
  
  tasks:
    # Delete Option Code
    - name: Delete Option Code
      b1_dhcp_option_code:
        name: "option-code-2"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: absent
