---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Gather ID for a given Option Code
    - name: Gather Option Code
      b1_dhcp_option_code_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: option_codes
    - debug: msg="{{ option_codes }}"