---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: Create an A Record
      b1_a_record:
        api_key: "{{ api }}"
        host: "{{ host }}"
        state : present
        zone : "qa-zone-1"
        address : "30.0.0.15"
        tags:
          - Name: "QA"
        name : "test-a-record"
        comment : "A record created by QA"