---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: Update an A Record
      b1_a_record:
        api_key: "{{ api }}"
        host: "{{ host }}"
        state : present
        zone : "qa-zone-1"
        address: 30.0.0.15
        name: '{"new_name": "test-record-updated", "old_name": "Test-Record"}'
        tags:
          - Name2: "QA"
        comment : "A record updated by QA"