---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    # Delete the IP space
    - name: Delete IP space
      b1_ipam_ip_space:
        name: "qa-space-1"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: absent