---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Gather ID for a given IP space
    - name: Gather IP space
      b1_ipam_ip_space_gather:
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: gather
      register: ip_spaces
    - debug: msg="{{ ip_spaces }}"