---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: Update a PTR Record
      b1_ptr_record:
        api_key: "{{ api }}"
        host: "{{ host }}"
        state : present
        zone : "qa-zone-1"
        tags:
          - Name: "QA"
        name: '{"new_name": "test-ptr-updated", "old_name": "test-ptr-record"}'
        comment : "PTR record updated by QA"
        address : "22.22.33.33"