---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ host_server }}"
  - api: "{{ api_key }}"

  tasks:
    #  Create a given IP space
    - name: Create IP space
      b1_ipam_ip_space:
        name: "Test-Ansible-Space"
        tags:
          - "Org": "Infoblox"
          - "Dept": "Engineering"
        comment: "This is a test IPSpace to validate Infoblox Ansible Collection"
        host: "{{ host_server }}"
        api_key: "{{ api }}"
        state: present

    # Update the IP space
    - name: Update the IPSpace
      b1_ipam_ip_space:
        name: "Test-Ansible-Space"
        tags:
          - "Status": "Working"
          - "GeoLoc": "India"
        host: "{{ host_server }}"
        api_key: "{{ api }}"
        state: present

#    # Delete the IP space
#    - name: Delete IP space
#      b1_ipam_ip_space:
#        name: "Test-Ansible-Space"
#        host: "{{ host_server }}"
#        api_key: "{{ api }}"
#        state: absent