---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ host_server }}"
  - api: "{{ api_key }}"

  tasks:

    #  Create a Range in a given subnet
    - name: Create Range in a given IP Space
      b1_ipam_range:
        space: "Test-Ansible-Space"
        name: "Test-Ansible-Range1"
        start: "172.16.0.100"
        end: "172.16.0.200"
        comment: "This is the test AB creation"
        dhcp_host: "ZTP_amit_ansible_2098146097655903253"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Update the Range in a given IP space
    - name: Update an existing Range.
      b1_ipam_range:
        space: "Test-Ansible-Space"
        start: '{"new_address": "172.16.0.50", "old_address": "172.16.0.100"}'
        end: '{"new_address": "172.16.0.150", "old_address": "172.16.0.200"}'
        name: "Test-Ansible-range1-mod"
        comment: "This is the test AB creation-mod"
        tags:
          - "Org": "Infoblox"
          - "Dept": "Engineering"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Delete the Range in a given IP space
    - name: Delete an existing Subnet.
      b1_ipam_range:
        space: "Test-Ansible-Space"
        start: "172.16.0.50"
        end: "172.16.0.150"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: absent
