---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ host_server }}"
  - api: "{{ api_key }}"

  tasks:
    #  Create a Subnet in a given IP space
    - name: Create Subnet in a given IP Space
      b1_ipam_subnet:
        space: "Test-Ansible-Space"
        address: '172.16.0.0/24'
        name: "Test-Ansible-Subnet1"
        comment: "This is the test AB creation"
        dhcp_host: "ZTP_amit_ansible_2098146097655903253"
        dhcp_options: 
          - routers: "172.16.0.1"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Update the Subnet in a given IP space
    - name: Update an existing Subnet.
      b1_ipam_subnet:
        space: "Test-Ansible-Space"
        address: '{"new_address": "172.16.0.64/27", "old_address": "172.16.0.64/24"}'
        name: "Test-Ansible-Subnet1-mod"
        comment: "This is the test AB creation-mod"
        tags:
          - "Org": "Infoblox"
          - "Dept": "Engineering"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Create a subnet in a given IP space using next_available_subnet
    - name: Create Subnet using next available function
      b1_ipam_subnet:
        address: '{"next_available_subnet": {"parent_block": "10.0.0.0/16", "cidr": "24", "count": "1"}}'
        space: Test-Ansible-Space
        name: "Test-Ansible-Subnet"
        comment: "This is the test AB creation"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present

    #  Delete the Subnet in a given IP space
    - name: Delete an existing Subnet.
      b1_ipam_subnet:
        space: "Test-Ansible-Space"
        address: '172.16.0.64/27'
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: absent
