---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: Create DNS Authoritative Zone
      b1_dns_auth_zone:
        fqdn: "qa-zone-1"
        view: "qa-view-1"
        primary_type: "cloud"
        internal_secondaries: 
          -  "ZTP_NIOS_TEST_4_14_8888544975683345166"
        tags:
          - Name: "QA"
        comment: "This zone is created by QA"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present