---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name : Gather View Information
      b1_dns_zone_gather:
        api_key: "{{ api }}"
        host: "{{ host }}"
        state : gather
        name : "qa-zone-1"
      register : dns_zone_lists
    - debug: msg="{{ dns_zone_lists }}"
