---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    - name: Update DNS Authoritative Zone
      b1_dns_auth_zone:
        fqdn: "qa-zone-1"
        view: "qa-view-1"
        internal_secondaries:
          - "ZTP_NIOS_TEST_4_14_8888544975683345166"
        tags:
          - Name: "updated_value"
        comment: "This is an update"
        api_key: "{{ api }}"
        host: "{{ host }}"
        state: present