---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "https://env-6.test.infoblox.com/"
  - api: "a466f5ed8e37bd51b4f1814a73601466"

  tasks:
    #  Create a Option Group
    - name: Create Option Group
      b1_ipam_option_group:
        name: "test1"
        tags:
          - "Org": "Infoblox"
          - "Dept": "QA"
        comment: "This is a test Optionspace to validate Infoblox Ansible Collection"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: present
        