---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    # Delete the Option Space
    - name: Delete Option Space
      b1_dhcp_option_space:
        name: "test"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: absent