---
- hosts: localhost
  connection: local
  collections:
    - infoblox.b1ddi_modules

  vars:
  - host: "{{ Host server to connect to }}"
  - api: "{{ api key to access the server }}"

  tasks:
    #  Update a Option Space
    - name: Update Option Space
      b1_dhcp_option_space:
        name: '{"new_name": "test1", "old_name": "test"}'
        tags:
          - "Org": "Infoblox"
          - "Dept": "QA"
        comment: "Updating the Optionspace"
        host: "{{ host }}"
        api_key: "{{ api }}"
        state: present
        
